### ISSUE TITLE
Version 0.4.7.11 is not available

### ISSUE THREAD

**Issue by abdrasulov** [guardianproject/tor-android#100]
When I tried to update tor-android to v.0.4.7.11 it fails with an error "Failed to resolve: info.guardianproject:tor-android:0.4.7.11"

I checked https://mvnrepository.com/artifact/info.guardianproject/tor-android. The latest version is 0.4.7.8.

I'd like to know how we can get v.0.4.7.11 in our project.

**Comment by n8fr8** [comment]
We had some delays with our Maven publishing pipeline.

You can build and include the AAR yourself as we've done in Orbot for now:
https://github.com/guardianproject/orbot/tree/master/tor-android

Otherwise, will work to have MVN updated early next week.

**Comment by uniqx** [comment]
@eighthave @n8fr8 To me this reads like the a job for the project maintainer/release manager. I neither received a crash course, nor do I have access rights to fill those roles. So I don't really understand how to contribute, please advice.

**Comment by n8fr8** [comment]
I'm going to take it over for now and get the gradle build publishing working directly.

**Comment by abdrasulov** [comment]
Hey @n8fr8. Is there any update?

**Comment by n8fr8** [comment]
Waiting for Sonatype to approve our gp build account, so we can push the artifacts.

**Comment by abdrasulov** [comment]
Hi folks. Is there any update?

**Comment by n8fr8** [comment]
I have full access to sonatype/mavencentral for publishing a new official release, and we will be putting 04.7.13 there as part of our next Orbot RC release in the next few days.
