### ISSUE TITLE
getting message this is HTTP Connect Tunnel, not an HTTP Proxy

### ISSUE THREAD

**Issue by MSajidJuneja** [guardianproject/tor-android#121]
when i visit onion links with http, i get this message this is HTTP Connect Tunnel, not an HTTP Proxy.

**Comment by MSajidJuneja** [comment]
@n8fr8 Can you please look into this issue?

**Comment by n8fr8** [comment]
Are you manually setting your proxy setting to 8118 or using some other custom configured proxy settings?

**Comment by MSajidJuneja** [comment]
@n8fr8 I am setting proxy via code in app like this.

`System.setProperty("java.net.useSystemProxies", true.toString())
System.setProperty(ProxyEnvVar.HTTP_PROXY_HOST.value, "127.0.0.1")
System.setProperty(ProxyEnvVar.HTTP_PROXY_PORT.value, "8118")
System.setProperty(ProxyEnvVar.HTTPS_PROXY_HOST.value, "127.0.0.1")
System.setProperty(ProxyEnvVar.HTTPS_PROXY_PORT.value, "8118")
System.setProperty(ProxyEnvVar.SOCKS_PROXY_HOST.value, "127.0.0.1")
System.setProperty(ProxyEnvVar.SOCKS_PROXY_PORT.value, "9050")`

**Comment by MSajidJuneja** [comment]
@n8fr8 Did you get a chance to look into this issue?

**Comment by n8fr8** [comment]
The Tor HTTP proxy only supports HTTPS traffic. That is just the way it is. Better to use the Orbot VPN feature or Tor browser for Android, if you really need to access HTTP traffic.

You can also just use the SOCKS proxy, since it will support HTTP and HTTPS.

**Comment by MSajidJuneja** [comment]
@n8fr8 Im using firefox android source and want to implement tor in it. Do you know how we can set in it so we can access HTTP links?

**Comment by n8fr8** [comment]
You can set SOCKS proxy directly in Firefox, and it will handle all HTTP and HTTPS traffic just fine. Don't use the HTTP proxy at all.

**Comment by MSajidJuneja** [comment]
@n8fr8 I have set proxy as mentioned in previous comment like this as I have to do it programmatically.

`System.setProperty("java.net.useSystemProxies", true.toString()) System.setProperty(ProxyEnvVar.SOCKS_PROXY_HOST.value, "127.0.0.1") System.setProperty(ProxyEnvVar.SOCKS_PROXY_PORT.value, "9050")`

It still does not work. I get error "cannot access network. check your proxy settings". I also tried Orbot VPN code and found that it disallows own package name in VPN builder, the app in which code for VPN is there. When i comment this disallow line, it cannot connect to tor network and says rejected socks error and i when dont comment any line, it connects but own app cannot access tor network. Can you please tell what can i do in these 2 scenarios? Using programmatically or using VPN code.
