### ISSUE TITLE
Update to tor 0.4.8 with PoW Defense

### ISSUE THREAD

**Issue by syphyr** [guardianproject/tor-android#123]
Tor 0.4.8 is now the latest stable release.  I have rebased the additional patches needed for Tor 0.4.8 here:
https://github.com/syphyr/tor/commits/release-0.4.8

Additionally, Tor 0.4.8 has a new feature called "PoW Defense" which acts as a new form of flood protection.  PoW Defense is enabled with the following additional commit:
https://github.com/syphyr/tor-android/commit/b60b622b106b0b42d55ae955521be1746d8b5a72

Initial tests of Tor 0.4.8 show that there is improved latency in Orbot with PoW Defense enabled.

**Comment by SkewedZeppelin** [comment]
bump?

both Tor Browser and Tails are now shipping 0.4.8.x:
- https://blog.torproject.org/new-release-tor-browser-130/
- https://gitlab.tails.boum.org/tails/tails/-/blob/master/debian/changelog#L83

and nearly 5,000 relays have updated: https://metrics.torproject.org/versions.html

The bigger feature of it, imo, is conflux which reduces latency in the send direction and increases throughput in the receive direction by using multiple "legs" for each circuit.

**Comment by uniqx** [comment]
I did re-base now, I guess we can continue the discussion here: https://github.com/guardianproject/tor/pull/4

**Comment by syphyr** [comment]
Completed via bc0c5e6d50fa7dfef5d19b317f8f43e9f7664a89
