### ISSUE TITLE
NPE in TorResourceInstaller.installResources Path

### ISSUE THREAD

**Issue by sisbell** [guardianproject/tor-android#13]
The code will throw an NPE if _TorNativeLoader.initNativeLibs_ can't find a file. _TorNativeLoader_ returns a null and then _TorResourceInstaller_ attempts to make this null value an executable.

**StackTrace**
04-01 04:25:17.306 13309 13372 E TorNativeLoader: Unable to find file in apk:lib/armeabi-v7a/tor
04-01 04:25:17.307 13309 13372 E Orbot   : Error installing Tor binaries
04-01 04:25:17.307 13309 13372 E Orbot   : java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.setReadable(boolean)' on a null object reference
04-01 04:25:17.307 13309 13372 E Orbot   : 	at org.torproject.android.binary.TorResourceInstaller.setExecutable(TorResourceInstaller.java:227)
04-01 04:25:17.307 13309 13372 E Orbot   : 	at org.torproject.android.binary.TorResourceInstaller.installResources(TorResourceInstaller.java:122)

**Comment by eighthave** [comment]
I should hopefully be making this moot with the TorService that loads libtor.so via the standard Android methods.
