### ISSUE TITLE
Which version of openSSL is used in this project ?

### ISSUE THREAD

**Issue by hkobir1** [guardianproject/tor-android#136]
I used this version: implementation 'info.guardianproject:tor-android:0.4.6.7'

After uploaded my app to play console warned like this:

Defective OpenSSL Version Your app uses a defective version of the OpenSSL library, 
which can cause your app to crash. Update to a fixed version of OpenSSL. Defective versions: OpenSSL 1.1.1b in lib/arm64-v8a/libtor.so

**Comment by bitmold** [comment]
That version of tor-android is out of date, but even if you bumped to the latest version we are in the midst of creating a new release with openssl3 and the latest binary of tor.

**Comment by hkobir1** [comment]
thanks Guardianproject/Tor-Android
