### ISSUE TITLE
misunderstanding with arm64 binary

### ISSUE THREAD

**Issue by admzzz** [guardianproject/tor-android#15]
downloaded from https://github.com/n8fr8/tor-android/blob/master/tor-android-binary/src/main/libs/arm64-v8a/tor.so

```
$ readelf -h Downloads/tor.so
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           ARM
  Version:                           0x1
  Entry point address:               0x87084
  Start of program headers:          52 (bytes into file)
  Start of section headers:          7773456 (bytes into file)
  Flags:                             0x5000200, Version5 EABI, soft-float ABI
  Size of this header:               52 (bytes)
  Size of program headers:           32 (bytes)
  Number of program headers:         9
  Size of section headers:           40 (bytes)
  Number of section headers:         29
  Section header string table index: 26
```
can you provide an arm64 binary, pls?

**Comment by n8fr8** [comment]
Currently this is just a 32-bit binary that can still execute on a 64 bit system. Since we use the built in shared library unpacking logic in Android now, we needed something to be there.

We are aiming to build a full Android 64 bit binary asap, but again, this one works fine.

Do you have a specific need, or you just think the performance will improve?

**Comment by Gedsh** [comment]
> Do you have a specific need, or you just think the performance will improve?
Yes, performance improvement expected with 64 bit native support. Thanks for response.  Will wait for real 64 bit binary.
