### ISSUE TITLE
Tor static binary

### ISSUE THREAD

**Issue by T0m14** [guardianproject/tor-android#26]
Hi,
I would like to report an issue when cross-compiling the Tor binary with the `--with-openssl-dir` option, which is mandatory when the `--enable-static` option is enabled.

There is a problem within the `external/tor/configure.ac` which prevents the openssl library to be correctly detected. I don't know whether to open the issue here or directly in the Tor repository, but as 99% of users here are cross-compiling from an x86 host, maybe it makes more sense to open the issue here.

The issue is in the line 937 : 

` [if (getenv("THIS_SHOULDNT_BE_SET_X201803")) SSL_CIPHER_get_id((void *)0);], [],`

This test wouldn't work when cross-compiling, as the arm64 openssl library would fail to load on the x86 host, and thus making the ./configure fail.

Removing the test by replacing the line by :

`   [;], [],`

Make it works, and then Tor can be cross-compiled successfully with the static mode enabled.

Thank you

**Comment by eighthave** [comment]
What OS were you running the build on?  I haven't run into this.  Also, I recently overhauled the build, that's visible in https://github.com/eighthave/tor-android until it gets merged.

**Comment by eighthave** [comment]
If you can provide more info, please reopen.  Also, check out the latest commits which completely overhaul the build process
