### ISSUE TITLE
Publish to jcenter 

### ISSUE THREAD

**Issue by remmerw** [guardianproject/tor-android#37]
Any chance of publishing the tor binaries to jcenter? 
Background: When it is published on jcenter, then it might be easier to publish apps on fdroid.
(Fdroid complains about  

repositories {
        maven { url "https://raw.githubusercontent.com/guardianproject/gpmaven/master" }
    }
)

**Comment by eighthave** [comment]
Even better, its coming to Maven Central:

https://repo1.maven.org/maven2/info/guardianproject/tor-android
