### ISSUE TITLE
Crashes when opening tabs

### ISSUE THREAD

**Issue by Thewisem** [guardianproject/tor-android#38]
A favourite Tor user here.
I want to inform that I have been having crashes when opening tabs
My guess is around 12-15 tabs opened and running in the background whould automatically crash the app. My devie is a samsung galaxt Tab A. And Best wishes from my side to the Tor project

**Comment by bitmold** [comment]
Seems like this crash pertains to Tor Browser for Android which is not what this project is (the names are all similar and kind of misleading) 

For bugs with Tor Browser you can report them here https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues
