### ISSUE TITLE
Tor 0.4.5.9

### ISSUE THREAD

**Issue by SkewedZeppelin** [guardianproject/tor-android#41]
Please bump to 0.4.5.9 as there are numerous security issues in 0.4.5.7.
https://blog.torproject.org/node/2041

The 12 patches on top of Tor cleanly rebase.
I'd open PR, but you can't create new tags/branches in one.
https://github.com/SkewedZeppelin/tor/commits/tor-android-0.4.5.9

**Comment by eighthave** [comment]
I also fixed a couple reproducible build bugs while I was at it, hopefully these two builds generate the same thing:
* https://gitlab.com/eighthave/tor-android/-/pipelines/325182476
* https://gitlab.com/guardianproject/tor-android/-/pipelines/325183495

**Comment by eighthave** [comment]
Its available on Maven Central now.
