### ISSUE TITLE
Proxy server refused connection

### ISSUE THREAD

**Issue by Hackerboi69420** [guardianproject/tor-android#49]
When opening a link before connecting to tor connection fails and Proxy server refused connection error shows.

When opening tor with "search the web" widget the url bar shows, and when something entered after few seconds the same error appears.

The tor widget preview (before drag and dropping into your launcher has the firefox icon) when the widget is placed onto homescreen the icon turns into the tor icon

Suggested fixes for the proxy server error: check if the proxy is connected to tor or if orbot is running and if not show the commect to tor screen

![Widget preview](https://user-images.githubusercontent.com/61636799/126743602-a629ce0c-67e9-4745-84f5-27ec522f20c4.jpg)

![Screen after opening tor with the widget](https://user-images.githubusercontent.com/61636799/126743853-a8bbc8d9-7390-4c99-bb98-a3e7dfbcdc3b.jpg)

**Comment by n8fr8** [comment]
is this a bug report for Tor Browser for Android? If so, you are in the wrong place.

**Comment by Hackerboi69420** [comment]
Yes it was supposed to be a bug report... Could you link me a bug report page?
