### ISSUE TITLE
Access to the Tor ControlPort

### ISSUE THREAD

**Issue by hsjoberg** [guardianproject/tor-android#54]
Hi, I am trying to make tor-android work together with another application ([lnd](https://github.com/lightningnetwork/lnd)) which requires access to the control port in order to spin up an onion service.

Going through the source code of TorService, it's not entirely clear to me if it's possible to gain access ControlPort in some capacity. Basically  I would like to give lnd the port together with some authentication method, just like you would with the normal Tor daemon on a PC.

**Comment by n8fr8** [comment]
The best place to see an integrated tor-android implementation is in Orbot itself. You can bind to the TorService to get direct access to the control port:
https://gitlab.com/guardianproject/orbot/-/blob/master/orbotservice/src/main/java/org/torproject/android/service/OrbotService.java#L757
