### ISSUE TITLE
HTTP not working

### ISSUE THREAD

**Issue by sahabuddinsk** [guardianproject/tor-android#69]
only https working, not working http tunel

**Comment by eighthave** [comment]
If you are using the HTTP CONNECT proxy, that will not work with HTTP, only HTTPS.  You need to run a full HTTP proxy if you want to proxy HTTP.

**Comment by sahabuddinsk** [comment]
@eighthave Can You Help Me with This

**Comment by akash-s-simformsolutions** [comment]
@eighthave  :  can you please help here. how you set HTTP CONNECT.

We are getting same issue as "this is an http connect tunnel, not an http proxy"
