### ISSUE TITLE
Where is the JNI's implementation?

### ISSUE THREAD

**Issue by dynfactor** [guardianproject/tor-android#74]
I have been browsing the codebase the last few weeks to see how you build tor and I have been seeing that the [tor source code](https://github.com/guardianproject/tor) used for building is pretty old (last update was +3 years ago?!).

But as the same time I see commits says like ["upgrade to"](https://github.com/guardianproject/tor-android/tree/master/external) commit once [every while](https://github.com/guardianproject/tor-android/commits/master/external) , [last one](https://github.com/guardianproject/tor-android/commit/7e6cffd6adc5b0d62b104029148bc42694761926)  was by @eighthave.
It seems insane cause its just the same code, isn't?

Also I was expecting to find to find some jni implemention in tor source code, for example, for [`run_main`](https://github.com/guardianproject/tor-android/blob/7e6cffd6adc5b0d62b104029148bc42694761926/tor-android-binary/src/main/java/org/torproject/jni/TorService.java#L194) like `jni_com_example_tor_main` but I couldn't find it either...

So, where can I find the JNI implementations?
Thanks in advance!

**Comment by eighthave** [comment]
Look at the `tor-android-*` tags in https://github.com/guardianproject/tor to see the code we are using.  That's where you'll also find the JNI implementation.  The _master_ branch is not updated in our tor fork.

**Comment by dynfactor** [comment]
Thanks you!
I found it [https://github.com/guardianproject/tor/tree/tor-android-0.4.7.4/src/feature/api](https://github.com/guardianproject/tor/tree/tor-android-0.4.7.4/src/feature/api) :)
