### ISSUE TITLE
unsupported flags DT_FLAGS_1=0x8000001 (<=Nougat)

### ISSUE THREAD

**Issue by syphyr** [guardianproject/tor-android#93]
After the NDK was updated to 25 (from this a6fbf7f64eaeb078ca37849cd19f630c9c44d6af) there are new linker warnings on <= Nougat. 

E GoLog   : WARNING: linker: /data/app/org.torproject.android-1/lib/arm64/libtor.so: unsupported flags DT_FLAGS_1=0x8000001

This issue was introduced by NDK r23b.

The android linker flags unused ELF sections as warnings now.  

Can this just be ignored?

**Comment by n8fr8** [comment]
Perhaps we need a different build for <= Nougat, but also will look into the flags

**Comment by syphyr** [comment]
Besides the new warning at runtime, it seems to be working ok on Nougat.  The new NDK 25 also shows a lot more warnings, especially when building openssl.

**Comment by syphyr** [comment]
Fixed with https://github.com/guardianproject/tor-android/pull/112
