### ISSUE TITLE
move to openssl 1.1.1 stable branch

### ISSUE THREAD

**Issue by syphyr** [guardianproject/tor-android#97]
I suggest we move to the openssl 1.1.1 stable branch (origin/OpenSSL_1_1_1-stable).  Currently, we are set on an outdated 1.1.1 tag anyway.  I have been testing latest stable 1.1.1 branch for a long time now without any issue.

**Comment by n8fr8** [comment]
good call

**Comment by syphyr** [comment]
Added PR https://github.com/guardianproject/tor-android/pull/98
